# Generated by Django 4.2.4 on 2023-10-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attack",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="defence",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="lucky",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="magic",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="power1",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="power2",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="power3",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
