# Generated by Django 4.2.4 on 2023-10-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0004_rename_power1_profile_value1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
