# Generated by Django 4.2.4 on 2023-10-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_profile_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="text",
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
