# Generated by Django 4.2.4 on 2023-10-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0006_alter_profile_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="completed",
            new_name="勾選重要裝備",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="important",
            new_name="已完成修改",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="text",
            new_name="輸入文字說明",
        ),
    ]
