# Generated by Django 4.2.4 on 2023-10-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0007_rename_completed_profile_勾選重要裝備_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="勾選重要裝備",
            new_name="completed",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="已完成修改",
            new_name="important",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="輸入文字說明",
            new_name="text",
        ),
    ]
