# Generated by Django 4.2.4 on 2023-10-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0008_rename_勾選重要裝備_profile_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="text",
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
