# Generated by Django 4.2.4 on 2023-10-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0009_alter_profile_date_completed_alter_profile_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="shopcart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
    ]
