# Generated by Django 4.2.4 on 2023-10-25 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0010_shopcart"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopcart",
            name="related_profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="profile.profile",
            ),
        ),
    ]
