# Generated by Django 4.2.4 on 2023-10-26 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0012_alter_shopcart_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='related_profile',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
