# Generated by Django 4.2.4 on 2023-10-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0014_profile_finalimgpath"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopcart",
            name="product_img",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
