# Generated by Django 4.2.4 on 2023-11-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0017_ordercart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercart",
            name="buy_way",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordercart",
            name="message_box",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordercart",
            name="ordernumber",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ordercart",
            name="totalPrice",
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
