# Generated by Django 4.2.4 on 2023-11-09 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0020_ordercart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopcart",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profile.ordercart",
            ),
        ),
    ]
