# Generated by Django 4.2.4 on 2023-11-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0021_shopcart_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopcart",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
